config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),    #127.0.0.1:8000/admin/
    path('poll/', include('poll.urls')), #127.0.0.1:8000/poll/
    path('', views.index),
    path('control/', include('control.urls'))
]

control/urls.py
from django.urls import path
from control import views
#네임 스페이스(소속공간)
app_name = 'control'

urlpatterns = [
    path('', views.index, name='index'), # 127.0.0.1:8000/poll/
    path('register/', views.register, name='register'),
    path('counter/', views.counter, name='counter'),
    path('calc_even_odd/', views.calc_even_odd, name='calc_even_odd'),
]

poll/urls.py
from django.urls import path
from poll import views
#네임 스페이스
app_name = 'poll'  #app_name변수에 poll앱 저장

urlpatterns = [
    path('', views.index, name='index'), # 127.0.0.1:8000/poll/
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

control/models.py
from django.db import models

# Create your models here.

poll/models.py
from django.db import models

# Question 모델(Model을 상속받음) - 테이블과 같은 의미
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):  #질문 내용이 문자로 출력됨
        return self.question_text

# Choice 모델
class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE) #외래키

    def __str__(self):
        return  self.choice_text

control/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'control/index.html')

#회원가입
def register(request):
    if request.method == "POST":
        #아이디를 넘겨 받음
        userid = request.POST['userid']
        return render(request, 'control/reg_result.html', {"userid":userid})
        #html로 렌더링할때 딕셔너리구조로 자료를 보냄
    else:       #GET이면 요청
        return render(request, 'control/register.html')

#반복문 forloop.counter
def counter(request):
    items = ['a', 'b', 'c', 'd']
    return render(request, 'control/counter.html', {'items':items})

#짝홀 판별
def calc_even_odd(request):
    if request.method == 'POST':
        try:
            num = int(request.POST['num'])
            #입력값(숫자-문자형)을 넘겨 받아 숫자형으로 변환
        except:
            return render(request, 'control/calc_even_odd.html',
                          {'error':'정수만 입력가능합니다.'})
        else:
            if num % 2 == 0:
                result = "짝수입니다."
            else:
                result = "홀수입니다."
            return render(request, 'control/calc_result.html',
                          {"num":num, 'result':result})
    else:
        return render(request, 'control/calc_even_odd.html')

poll/views.py
from django.http import HttpResponse
from django.shortcuts import render
from poll.models import Question

def index(request):
    # db에 있는 모든 데이터 조회하기(select)
    question_list = Question.objects.all()
    return render(request, 'poll/index.html', {'question_list':question_list})
    #return HttpResponse("Welcome~ 환영합니다!!")

def detail(request, question_id):
    # 해당 id(순번)로 자료 조회(select)
    question = Question.objects.get(id=question_id)
    return render(request, 'poll/detail.html', {'question':question})

def vote(request, question_id):
    question = Question.objects.get(id=question_id)
    #선택자료넘겨받음
    try:
        choice_id = request.POST['choice']
        sel_choice = question.choice_set.get(id=choice_id)
    except:
        return render(request, 'poll/detail.html',
                      {'question':question, 'error':'선택을 확인하세요.'})
    else:
        sel_choice.votes = sel_choice.votes + 1
        sel_choice.save()   #dbㅇㅔ 저장
        return render(request, 'poll/vote_result.html', {'question':question})

templates/control/calc_even_odd.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>짝수/홀수 판별</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {% if error %}
            <p>{{ error }}</p>
        {% endif %}
        <p>정수 입력 : </p>
        <p>
            <input type="text" name="num">
            <input type="submit" value="전송">
        </p>
    </form>
</body>
</html>

templates/control/calc_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>짝수/홀수 판정 결과</title>
</head>
<body>
    <h2>짝수/홀수 판정 결과</h2>
    <p>{{ num }}는(은) {{ result }}</p>
</body>
</html>

templates/control/counter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>반복문 index 예제</title>
</head>
<body>
    <h2>템플릿 태그 - forloop.counter 예제</h2>
    <!-- forloop.counter는 1,2,3의 번호를 붙일 때 사용
         for i in range(0 10)와 유사사 -->
    <!-- forloop.counter0은 0부터 시작 -->
    <ul>
    {% for item in items %}
        <li>{{ forloop.counter0 }} -- {{ item }}</li>
<!--        <li>{{ forloop.counter }} &#45;&#45; {{ item }}</li>-->
    {% endfor %}
    </ul>
    <ul>
        {% for item in items %}
            {% if forloop.counter < 3 %}
            <li>{{ forloop.counter }}번째 줄입니다. </li>
            {% endif %}
        {% endfor %}
    </ul>

    <h3>내장 템플릿 필터(filter) 태그 사용하기</h3>
    <p>forloop.counter|add:5</p>
    <ul>
        {% for item in items %}
            {% if forloop.counter < 3 %}
            <li>{{ forloop.counter|add:5 }}번째 줄입니다. </li>
            {% endif %}
        {% endfor %}
    </ul>
</body>
</html>

templates/control/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>view 제어 함수 연습</title>
</head>
<body>
    <h1>view 제어 함수 연습</h1>
    <ul>
        <li>127.0.0.1:8000/control/ 요청 -> 메인 페이지(index)</li>
        <li>127.0.0.1:8000/control/register 요청 -> 회원가입 </li>
        <li>127.0.0.1:8000/control/counter 요청 -> 반복문 예제 </li>
        <li>127.0.0.1:8000/control/calc_even_odd 요청 -> 짝수/홀수 판별 </li>
    </ul>
</body>
</html>

templates/control/reg_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>가입 결과</title>
</head>
<body>
    <h2>가입 결과</h2>
    <p>{{ userid }}님 환영합니다.</p>
</body>
</html>

templates/control/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>회원 가입</title>
</head>
<body>
  <h2>회원 가입</h2>
  <form action="" method="post">
      {% csrf_token %} <!-- 폼을 전송할 때 반드시 명시 : 보안 처리 필수 -->
      <p>
          <label for="userid">아이디</label>
          <input type="text" id="userid" name="userid">
      </p>
      <p><input type="submit" value="전송"></p>
  </form>
</body>
</html>

templates/poll/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>설문 상세 페이지</title>
<!--    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">-->
     <link rel="stylesheet" href="{% static 'poll/css/bootstrap.css' %}">
</head>
<body>
    <div class="container">
        <section>
            <div class="jumbotron">
                <div class="text-center">
                    <h1>투표 하기</h1>
                </div>
            </div>
            <h4 style="margin:20px 280px;">{{ question.question_text }}</h4>
            <form action="{% url 'poll:vote' question.id %}" method="post"
                  style="width:500px; margin: 0 auto;">
                {% csrf_token %}
                {% if error %}
                    <p style="font-size:1.2rem">{{ error }}</p>
                {% endif %}
                {% for choice in question.choice_set.all %}
                <p style="font-size:1.2rem">
                    <input type="radio" name="choice" id="choice" value="{{ choice.id }}">
                    <label for="choice">{{ choice.choice_text }}</label>
                </p>
                {% endfor %}
                <p><input type="submit" value="투표"></p>
            </form>
        </section>
    </div>
</body>
</html>

templates/poll/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>welcome~ polls</title>
<!--    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">-->
    <link rel="stylesheet" href="{% static 'poll/css/bootstrap.css' %}">
</head>
<body>
    <div class="container">
        <section>
            <div class="jumbotron">
                <div class="text-center">
                    <h1>설문 목록</h1>
                </div>
            </div>
            <div class="row">
                {% if question_list %}
                    {% for question in question_list %}
                    <div class="col-4">
                        <div class="card">
                            <div class="card-body">
            <!--        <a href="/poll/{{ question.id }}">{{ question.question_text }}</a>-->
                                <a href="{% url 'poll:detail' question.id %}">
                                    <h5 style="line-height: 2rem">{{ question.question_text }}</h5></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                <p>설문이 없습니다.</p>
                {% endif %}

            </div>
        </section>
    </div>
</body>
</html>

templates/poll/vote_result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>투표 결과</title>
<!--    <link rel="stylesheet" href="{% static 'poll/css/style.css' %}">-->
    <link rel="stylesheet" href="{% static 'poll/css/bootstrap.css' %}">
</head>
<body>
    <div class="container">
        <section>
            <div class="jumbotron">
                <div class="text-center">
                    <h1>투표 하기</h1>
                </div>
            </div>
            <h4 style="margin:20px 280px;">{{ question.question_text }}</h4>
            <ul style="width:500px; margin: 0 auto;">
                {% for choice in question.choice_set.all %}
                <li style="margin: 20px;">
                    {{ choice.choice_text }} -- {{choice.votes }}votes
                </li>
                {% endfor %}
            </ul>
        </section>
    </div>
</body>
</html>